news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('blog/<slug>', views.blog, name='blog'),
    path('details', views.details, name='details'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('main-menu-details/<name>', views.mainmenudetails, name='main-menu-details'),
    path('sub-menu-details/<name>', views.submenudetails, name='sub-menu-details'),
]

newsportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django. conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls'))
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

news/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager


class MainMenu(models.Model):
    created_at = models.DateField()
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    status = models.BooleanField(default=0)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    page_visit = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class SubMenu(models.Model):
    created_at = models.DateField()
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    main_menu = models.ForeignKey(MainMenu, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    status = models.BooleanField(default=0)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    page_visit = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Blog(models.Model):
    created_at = models.DateField()
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    main_menu = models.ForeignKey(MainMenu, on_delete=models.CASCADE, blank=True)
    sub_menu = models.ForeignKey(SubMenu, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    status = models.BooleanField(default=0)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    page_visit = models.IntegerField(default=0)
    tags = TaggableManager()

    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render, HttpResponse
from .models import *
from django.shortcuts import get_object_or_404

def index(request):
    data = {
        'allData': Blog.objects.all(),
        'fashionData':Blog.objects.filter(main_menu__name = 'Fashion')[:4],
        'latestData': Blog.objects.all().order_by('created_at')[:5],
        'popularPost':Blog.objects.all().order_by('-page_visit')[:4],
        'technologyData':Blog.objects.filter(main_menu__name = 'Fashion'),
        'sportsData': Blog.objects.filter(main_menu__name='Fashion')[:4],
        'sportsDataMax':Blog.objects.filter(main_menu__name='Fashion').order_by('-page_visit')[:1],
        'mobileData':Blog.objects.filter(main_menu__name = 'Mobile'),
    }
    return render(request, 'pages/index.html',data)


def blog(request, slug):
    related = get_object_or_404(Blog, slug=slug)
    data = {
        'title': Blog.objects.get(slug=slug),
        'menuDetails': Blog.objects.get(slug=slug),
        'popularPost': Blog.objects.all().order_by('-page_visit')[:4],
        'relatedPost': related.tags.similar_objects()
    }
    return render(request, 'pages/details.html',data)


def details(request):
    data={
        'popularPost': Blog.objects.all().order_by('-page_visit')[:4],
    }
    return render(request, 'pages/category.html',data)


def mainmenudetails(request, name):
    # main_menu: MainMenu.objects.get(slug=slug)
    # main_menu.page_visit += 1
    # main_menu.save()
    data = {
        'title': MainMenu.objects.get(name=name),
        'menuDetails': Blog.objects.filter(main_menu__name = name),
        'popularPost': Blog.objects.all().order_by('-page_visit')[:4],
    }
    return render(request, 'pages/category.html', data)


def submenudetails(request, name):
    data = {
        'title': SubMenu.objects.get(name=name),
        'menuDetails': Blog.objects.filter(sub_menu__name=name),
        'popularPost': Blog.objects.all().order_by('-page_visit')[:4],
    }
    return render(request, 'pages/category.html', data)

def contact(request):
    return render(request, 'pages/contact.html')

def about(request):
    return render(request, 'pages/about.html')

news/templates/layout/footer.html
{% load static %}
<footer id="footer">
    <div class="footer_top">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInLeftBig">
            <h2>Achyut's Blog</h2>
            <img src="{% static 'assets/images/logo.png' %}">
            <p style="float:right;">Achyut's Blog is news portal website</p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInDown">
            <h2>Main Pages</h2>
            <ul class="tag_nav">
              <li><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInRightBig">
            <h2>Contact</h2>
            <p>We are very happy, you are here with us, Read more article and have fun</p>
            <address>
            Tokha-11 Kathmandu Nepal, Achyut1324@gmail.com
              +977 9843450482
            </address>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_bottom">
      <p class="copyright">Copyright &copy; 2020 <a href="{% url 'home' %}">Achyut'S BLOG</a></p>
        <p class="copyright" style="text-align:right;">Developed By <a href="http://nachyut.com.np/">Achyut.An</a></p>
    </div>
  </footer>
</div>

{% load static %}

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.li-scroller.1.0.js' %}"></script>
<script src="{% static 'assets/js/jquery.newsTicker.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.fancybox.pack.' %}js"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>


</body>
</html>

news/templates/layout/header.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>
    {% if title %}
     {{title}}
    {% else %}
     welcome
    {% endif %}
</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href=" {% static 'assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/li-scroller.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
<!--[if lt IE 9]>
<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
<script src="{% static 'assets/js/respond.min.js' %}"></script>
<![endif]-->
</head>
<body>
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">

news/templates/layout/nav.html
  <section id="navArea">

    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav main_nav">
          <li class="active"><a href="{% url 'home' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
          {% for menu in MenuData %}
          {% if menu.status %}
          {% if menu.submenu_set.all %}
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{menu.name}}</a>
            <ul class="dropdown-menu" role="menu">
              {% for sub in menu.submenu_set.all %}
              <li><a href="{% url 'sub-menu-details' sub.name %}">{{sub.name}}</a></li>
            {% endfor %}
            </ul>
          </li>
          {% else %}
            <li><a href="{% url 'main-menu-details' menu.name %}">{{menu.name}}</a></li>
          {% endif %}
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </nav>
  </section>

news/templates/layout/top-header.html
{% load static %}
<header id="header">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_top">
          <div class="header_top_left">
            <ul class="top_nav">
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
          </div>
          <div class="header_top_right">
            <p>{% now ' Y M d  '%}</p>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_bottom">
          <div class="logo_area"><a href="{%url 'home' %}" class="logo"><img src="" alt="">Achyut's Blog</a></div>
          <div class="add_banner"><a href="#"><img src="images/addbanner_728x90_V1.jpg" alt=""></a></div>
        </div>
      </div>
    </div>
  </header>

news/templates/master/master.html
{% include 'layout/header.html' %}
{% include 'layout/top-header.html' %}
{% include 'layout/nav.html' %}
{% include 'layout/top-news.html' %}
{% block content %}

{% endblock %}
{% include 'layout/footer.html' %}

news/templates/pages/about.html
{% extends 'master/master.html' %}
{% block content %}
{% load static %}
<style>
    .image{
    width:100%;
    }
    ul li {
    padding:3px;
    color:#346;
    }
</style>

<section id="contentSection">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <h1>About Me </h1>
            <hr>
            <p>I’m an enthusiastic Developer who has been working on WordPress and blogger for the past 2 years. I love
                playing with HTML, CSS, JS and love implementing the graphical design into beautiful code by combining
                the art of design with the art of programming to make a beautiful website. Currently, I am studying
                Bsc.CSIT in trinity international College</p>
            <hr>
            <h2>My Recent Projects</h2>
            <hr>
            <ul>
                <h4>
                <li>Naya Gadgets</li>
                <li>Colz Life</li>
                <li>Resto Menu System </li>
                <li>Online Shop </li>
                    </h4>
            </ul>
            <hr>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-8">
            <img class="image" src="{% static 'assets/images/image.jpg'%}">
        </div>
    </div>
</section>
{% endblock %}

news/templates/pages/category.html
{% extends 'master/master.html' %}
{% block content %}
{% load static %}
<section id="contentSection">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="left_content">
                <div class="single_page">

                    <h2><span>Popular Post</span></h2>
                    <hr>
                    <ul class="spost_nav">
                        {% for data in menuDetails %}
                        <li>
                            <div class="media wow fadeInDown"><a href="single_page.html" class="media-left"> <img alt=""
                                     src="{{ data.image.url }}"></a>
                                <div class="media-body"><a href="{% url 'blog' data.slug %}" class="catg_title"><h4>{{data.title}}</h4></a>
                                    <div class="post_commentbox"><a href="#"><i class="fa fa-user"></i>{{data.posted_by}}</a> <span><i
                            class="fa fa-calendar"></i>{{data.created_at}}</span> <a href="#"><i
                            class="fa fa-tags"></i>{{data.main_menu}}</a></div>
                                    <p> {{data.description |truncatewords:35 |safe }}</p></div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <aside class="right_content">
                <div class="single_sidebar">
                    <h2><span>Popular Post</span></h2>
                    <ul class="spost_nav">
                        {% for popular in popularPost %}
                        <li>
                            <div class="media wow fadeInDown"><a href="{% url 'blog' popular.slug %}" class="media-left"> <img alt=""
                                                                                                                  src="{{popular.image.url}}">
                            </a>
                                <div class="media-body"><a href="{% url 'blog' popular.slug %}" class="catg_title"> {{popular.title}}</a></div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="single_sidebar wow fadeInDown">
                    <h2><span>Links</span></h2>
                    <ul>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Rss Feed</a></li>
                        <li><a href="#">Login</a></li>
                        <li><a href="#">Life &amp; Style</a></li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</section>

{% endblock %}

news/templates/pages/contact.html
{% extends 'master/master.html' %}
{% block content %}
{% load static %}
<style>
    *{
  margin: 0;
  padding: 0;
  font-family: "montserrat",sans-serif;
}
.contact-section{
  background: url(bg.png) no-repeat center;
  background-size: cover;
  padding: 40px 0;
}
.contact-section h1{
  text-align: center;
  color: #ddd;
}
.border{
  width: 100px;
  height: 10px;
  background: #34495e;
  margin: 40px auto;
}

.contact-form{
  max-width: 600px;
  margin: auto;
  padding: 0 10px;
  overflow: hidden;
}

.contact-form-text{
  display: block;
  width: 100%;
  box-sizing: border-box;
  margin: 16px 0;
  border: 0;
  background: #111;
  padding: 20px 40px;
  outline: none;
  color: #ddd;
  transition: 0.5s;
}
.contact-form-text:focus{
  box-shadow: 0 0 10px 4px #34495e;
}
textarea.contact-form-text{
  resize: none;
  height: 120px;
}
.contact-form-btn{
  float: right;
  border: 0;
  background: #34495e;
  color: #fff;
  padding: 12px 50px;
  border-radius: 20px;
  cursor: pointer;
  transition: 0.5s;
}
.contact-form-btn:hover{
  background: #2980b9;
}

</style>
<section id="contentSection">
    <div class="contact-section">
        <h1>Contact Us</h1>
         <p style="text-align:center;">We are here for your support and love, Please contact us via E-mail or below form </p>
        <div class="border"></div>
        <form class="contact-form" action="index.html" method="post">
            <input type="text" class="contact-form-text" placeholder="Your name">
            <input type="email" class="contact-form-text" placeholder="Your email">
            <input type="text" class="contact-form-text" placeholder="Your phone">
            <textarea class="contact-form-text" placeholder="Your message"></textarea>
            <input type="submit" class="contact-form-btn" value="Send">
        </form>
    </div>
</section>
{% endblock %}

news/templates/pages/details.html
{% extends 'master/master.html' %}
{% block content %}
{% load static %}
<section id="contentSection">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="left_content">
                <div class="single_page">
                    <ol class="breadcrumb">
                        <li><a href="{%url 'home'%}">Home</a></li>
                        {%if menuDetails.main_menu %}
                        <li><a href="#">{{ menuDetails.main_menu }}</a></li>
                        {%endif%}
                    </ol>
                    <h1>{{ menuDetails.title }}</h1>
                    <div class="post_commentbox"><a href="#"><i class="fa fa-user"></i>{{menuDetails.posted_by}}</a>
                        <span><i
                                class="fa fa-calendar"></i>{{menuDetails.created_at}}</span> <a href="#"><i
                                class="fa fa-tags"></i>{{menuDetails.main_menu}}</a></div>
                    <div class="single_page_content"><img class="img-center" src="{{ menuDetails.image.url }}" alt="">
                        {{ menuDetails.description | safe }}

                        <hr>
                        <button class="btn default-btn">Default</button>
                        <button class="btn btn-red">Red Button</button>
                    </div>
                    <div class="social_link">
                        <ul class="sociallink_nav">

                            <li><a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"><i class="fa fa-facebook"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        </ul>
                    </div>
                    <div class="related_post">
                        <h2>Related Post <i class="fa fa-thumbs-o-up"></i></h2>
                        <ul class="spost_nav wow fadeInDown animated">
                            {% for related in relatedPost%}
                            <li>
                                <div class="media"><a class="media-left" href="single_page.html"> <img
                                        src="../images/post_img1.jpg" alt=""> </a>
                                    <div class="media-body"><a class="catg_title" href="{% url 'blog' related.slug %}">{{related.title}}</a>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="nav-slit"><a class="prev" href="#"> <span class="icon-wrap"><i class="fa fa-angle-left"></i></span>
            <div>
                <h3>City Lights</h3>
                <img src="{% static 'assets/images/post_img1.jpg' %}" alt=""/></div>
        </a> <a class="next" href="#"> <span class="icon-wrap"><i class="fa fa-angle-right"></i></span>
            <div>
                <h3>Street Hills</h3>
                <img src="../images/post_img1.jpg" alt=""/></div>
        </a></nav>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <aside class="right_content">
                <div class="single_sidebar">
                    <h2><span>Popular Post</span></h2>
                    <ul class="spost_nav">
                        {% for popular in popularPost %}
                        <li>
                            <div class="media wow fadeInDown"><a href="{% url 'blog' popular.slug %}"
                                                                 class="media-left"> <img alt=""
                                                                                          src="{{popular.image.url}}">
                            </a>
                                <div class="media-body"><a href="{% url 'blog' popular.slug %}" class="catg_title">{{popular.title}}</a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="single_sidebar wow fadeInDown">
                    <h2><span>Links</span></h2>
                    <ul>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Rss Feed</a></li>
                        <li><a href="#">Login</a></li>
                        <li><a href="#">Life &amp; Style</a></li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</section>
{% endblock %}